In [28]:
#Import dependencies
import path
import glob
import pandas as pd
import datetime
import pytz

In [33]:
#Loop thru CSV files for parking violations, and add to DataFrame
moving_list_ = []

moving_path = 'Moving_Violations_2018'
moving_allFiles = glob.glob(moving_path + "/*.csv")

for moving_file_ in moving_allFiles:
   df = pd.read_csv(moving_file_,index_col=None, header=0)
   moving_list_.append(df)

moving_df = pd.concat(moving_list_, axis = 0, ignore_index = True)

moving_df.head()

/Users/thomasdirienzo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # This is added back by InteractiveShellApp.init_path()

,ACCIDENTINDICATOR,ADDRESS_ID,AGENCYID,FINEAMT,LOCATION,OBJECTID,PENALTY1,PENALTY2,ROW_,ROW_ID,STREETSEGID,TICKETISSUEDATE,TICKETTYPE,TOTALPAID,VIOLATIONCODE,VIOLATIONDESC,XCOORD,YCOORD
0,No,31943.0,25.0,100,3700 BLK SOUTHERN AVE SE SW/B,15293004,0,NaN,NaN,NaN,1435.0,2018-11-02T11:13:00.000Z,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,404133.5400,132428.0100
1,No,814983.0,25.0,100,3RD ST TUNNEL NW N/B BY MA AVE,15293005,0,NaN,NaN,NaN,6364.0,2018-11-12T07:15:00.000Z,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,398788.1561,136798.6603
2,No,807819.0,25.0,100,5200 BLK 14TH ST NW S/B,15293006,0,NaN,NaN,NaN,6705.0,2018-11-10T09:22:00.000Z,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,397102.6300,142844.3000
3,No,805065.0,25.0,100,2200 BLOCK K ST NW E/B,15293007,0,NaN,NaN,NaN,4361.0,2018-11-16T10:10:00.000Z,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900
4,No,805065.0,25.0,100,2200 BLK K ST NW W/B,15293008,0,NaN,NaN,NaN,4361.0,2018-11-16T10:15:00.000Z,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900

In [36]:
est = pytz.timezone('US/Eastern')
utc = pytz.utc
fmt = '%Y-%m-%d %H:%M:%S %Z%z'

moving_df['TICKETISSUEDATE'] = moving_df['TICKETISSUEDATE'].apply(lambda x:x.astimezone(est).strptime(fmt))

AttributeError: 'str' object has no attribute 'astimezone'

In [25]:
moving_df['TICKETISSUEDATE'] = pd.to_datetime(moving_df['TICKETISSUEDATE'])

#Set index to date, and add date column
moving_df = moving_df.set_index(pd.DatetimeIndex(moving_df['TICKETISSUEDATE']))

moving_df['Date'] = moving_df.index.date

moving_df.head()

,ACCIDENTINDICATOR,ADDRESS_ID,AGENCYID,FINEAMT,LOCATION,OBJECTID,PENALTY1,PENALTY2,ROW_,ROW_ID,STREETSEGID,TICKETISSUEDATE,TICKETTYPE,TOTALPAID,VIOLATIONCODE,VIOLATIONDESC,XCOORD,YCOORD,Date
TICKETISSUEDATE,,,,,,,,,,,,,,,,,,,
2018-11-02 11:13:00+00:00,No,31943.0,25.0,100,3700 BLK SOUTHERN AVE SE SW/B,15293004,0,NaN,NaN,NaN,1435.0,2018-11-02 11:13:00+00:00,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,404133.5400,132428.0100,2018-11-02
2018-11-12 07:15:00+00:00,No,814983.0,25.0,100,3RD ST TUNNEL NW N/B BY MA AVE,15293005,0,NaN,NaN,NaN,6364.0,2018-11-12 07:15:00+00:00,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,398788.1561,136798.6603,2018-11-12
2018-11-10 09:22:00+00:00,No,807819.0,25.0,100,5200 BLK 14TH ST NW S/B,15293006,0,NaN,NaN,NaN,6705.0,2018-11-10 09:22:00+00:00,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,397102.6300,142844.3000,2018-11-10
2018-11-16 10:10:00+00:00,No,805065.0,25.0,100,2200 BLOCK K ST NW E/B,15293007,0,NaN,NaN,NaN,4361.0,2018-11-16 10:10:00+00:00,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900,2018-11-16
2018-11-16 10:15:00+00:00,No,805065.0,25.0,100,2200 BLK K ST NW W/B,15293008,0,NaN,NaN,NaN,4361.0,2018-11-16 10:15:00+00:00,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900,2018-11-16

In [31]:
est = pytz.timezone('US/Eastern')
utc = pytz.utc
fmt = '%Y-%m-%d %H:%M:%S %Z%z'

moving_df['TICKETISSUEDATE'] = moving_df['TICKETISSUEDATE'].apply(lambda x:x.astimezone(est).strftime(fmt))

TypeError: Cannot convert tz-naive Timestamp, use tz_localize to localize

In [27]:
moving_df.head()

,ACCIDENTINDICATOR,ADDRESS_ID,AGENCYID,FINEAMT,LOCATION,OBJECTID,PENALTY1,PENALTY2,ROW_,ROW_ID,STREETSEGID,TICKETISSUEDATE,TICKETTYPE,TOTALPAID,VIOLATIONCODE,VIOLATIONDESC,XCOORD,YCOORD,Date
TICKETISSUEDATE,,,,,,,,,,,,,,,,,,,
2018-11-02 11:13:00+00:00,No,31943.0,25.0,100,3700 BLK SOUTHERN AVE SE SW/B,15293004,0,NaN,NaN,NaN,1435.0,2018-11-02,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,404133.5400,132428.0100,2018-11-02
2018-11-12 07:15:00+00:00,No,814983.0,25.0,100,3RD ST TUNNEL NW N/B BY MA AVE,15293005,0,NaN,NaN,NaN,6364.0,2018-11-12,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,398788.1561,136798.6603,2018-11-12
2018-11-10 09:22:00+00:00,No,807819.0,25.0,100,5200 BLK 14TH ST NW S/B,15293006,0,NaN,NaN,NaN,6705.0,2018-11-10,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,397102.6300,142844.3000,2018-11-10
2018-11-16 10:10:00+00:00,No,805065.0,25.0,100,2200 BLOCK K ST NW E/B,15293007,0,NaN,NaN,NaN,4361.0,2018-11-16,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900,2018-11-16
2018-11-16 10:15:00+00:00,No,805065.0,25.0,100,2200 BLK K ST NW W/B,15293008,0,NaN,NaN,NaN,4361.0,2018-11-16,Moving,100.0,T119,SPEED 11-15 MPH OVER THE SPEED LIMIT,395664.9200,137186.8900,2018-11-16